version: "3.8"

services:
  rtsp:
    build: ./services/rtsp
    container_name: rtsp-server
    privileged: true
    runtime: nvidia
    network_mode: host
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
  server:
    build: ./services/server
    container_name: nami-server
    ports:
      - "8000:8000"          
      - "5005:5005/udp"      
    depends_on:
      - webrtc

  webrtc:
    image: mpromonet/webrtc-streamer:latest
    container_name: webrtc-streamer
    ports:
      - "8001:8000"
    command: ["-n", "camera", "-u", "rtsp://192.168.100.70:8554/test"]

