services:
  api:
    build: ./services/api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./images:/images

  viewer:
    build: ./services/viewer
    container_name: viewer
    depends_on:
      - api
