services:
  api:
    build: ./services/api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./images:/images
    devices:
      - "/dev/video0:/dev/video0"
    runtime: nvidia 